spring:
  application:
    name: spring-jwt
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: ob11to
    password: ob11to
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret:
    access: czhuUGpleERKNHQ2ZnNJVUlVaGhYcWxrdFhqWGRrY3l5Z0RWVjVJZXBZcUJUbXY0b1hGRlIyR3drSXhCTXpyN09FSFhFSGQzN3c9PQ==
    refresh: ekwydmZ5bm92eHJmL2twRjlPMm00TkNXS0pvT05TVEpQLzdzOUoyakVHM2lmaUtDR3lsYVo4ZkRlM1BjaDA1QXdBekthdzlyT01OZz09