spring:
  application:
    name: spring-jwt
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: ob11to
    password: ob11to
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true